name: Dependency Update

on:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at midnight UTC
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Update dependencies
      run: |
        # Update all packages to latest versions
        dotnet list package --outdated --format json > outdated.json
        if [ -s outdated.json ]; then
          echo "Outdated packages found"
          # This is a placeholder - you might want to use a tool like dependabot
          # For now, we'll just create an issue if updates are available
        fi

    - name: Create issue if updates available
      uses: actions/github-script@v7
      if: success()
      with:
        script: |
          const fs = require('fs');
          if (fs.existsSync('outdated.json')) {
            const outdated = JSON.parse(fs.readFileSync('outdated.json', 'utf8'));
            if (outdated.projects && outdated.projects.length > 0) {
              github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Dependency Updates Available',
                body: 'Automated check found outdated dependencies. Please review and update manually.',
                labels: ['dependencies']
              });
            }
          }